### ISSUE TITLE
[bug]pythonfind

### ISSUE THREAD

**Issue by username4gh** [username4gh/dotfiles#61]
Traceback (most recent call last):
  File "/Users/xxx/.dotfiles/bin/pythonfind", line 508, in <module>
    main()
  File "/Users/xxx/.dotfiles/bin/pythonfind", line 493, in main
    search(query, options.dir)
  File "/Users/xxx/.dotfiles/bin/pythonfind", line 288, in search
    _search(query, directory, depth)
  File "/Users/xxx/.dotfiles/bin/pythonfind", line 272, in _search
    if not options.hidden and is_hidden(path):
  File "/Users/xxx/.dotfiles/bin/pythonfind", line 119, in is_hidden
    raise OSError('CFURLCopyResourcePropertyForKey failed')
OSError: CFURLCopyResourcePropertyForKey failed

**Comment by username4gh** [comment]
already got fixed by previous commit
